<a href="https://colab.research.google.com/github/AliK1977/DAwPython/blob/main/Stats_Assign_(Central_Tendency%26_Dispersion).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Descriptive Statistics

 Import **NumPy**, **SciPy**, and **Pandas**

In [2]:
import numpy as np
import scipy 
import pandas as pd


 Randomly generate 1,000 samples from the normal distribution using `np.random.normal()`(mean = 100, standard deviation = 15)

In [42]:
samples =np.random.normal(100,15,1000)
samples


array([ 68.01878023, 117.45624542, 118.2826951 ,  77.36109727,
        92.24476403,  88.95332395, 112.93806233,  84.90422999,
        73.42631771,  96.82706483, 107.06390837, 111.6680249 ,
       111.86296185, 123.35034277,  98.46763949, 100.18227419,
        80.24254198, 106.67371091,  88.61241964, 116.65827501,
        96.43572406,  96.75182011,  99.8470952 , 102.3382465 ,
       102.41427814,  81.52887654,  87.25140098, 108.30325529,
        94.92402011, 133.1381545 ,  80.81721772, 103.46684086,
        95.27809179,  87.39558434,  87.3788459 ,  87.51937365,
       139.81683413,  95.60450916,  94.57468219,  93.39898839,
        69.1398248 ,  71.15706212, 107.03699919,  79.88704161,
       118.96597292,  95.38227812, 108.481236  ,  92.62569283,
        81.31210974, 102.75819704, 138.3150673 , 108.37248166,
        81.2530295 , 113.05359748,  96.33901763,  90.47064987,
       105.62654786, 119.61088388, 129.30024348, 113.43726715,
       116.75059087, 116.48978328, 104.413773  , 127.32

Compute the **mean**, **median**, and **mode**

In [43]:
from numpy.lib.function_base import median
import numpy as np
from scipy import stats

mean_samples = np.mean(samples)
print("mean:", mean_samples)

median_samples = np.median(samples)
print("median:", median_samples)

mode_samples= stats.mode(samples)
print("mode:",mode_samples)

mean: 99.25380799503749
median: 99.69882514712197
mode: ModeResult(mode=array([56.69639169]), count=array([1]))


Compute the **min**, **max**, **Q1**, **Q3**, and **interquartile range**

In [35]:
print("Min: ", (np.min(samples)))

print("Max: ", (np.max(samples)))

print("Q1:", (np.percentile(samples, 25)))

print("Q2:", (np.percentile(samples, 50)))  

print("Q3:", (np.percentile(samples, 75)))

print("IQR:", (stats.iqr(samples)))

Min:  49.82334746571749
Max:  146.29994586107665
Q1: 88.97912450834366
Q2: 98.97025521409824
Q3: 109.45361076617581
IQR: 20.474486257832154


Compute the **variance** and **standard deviation**

In [36]:
print("Variance: ", (np.var(samples)))

print("Std: ", (np.std(samples)))

Variance:  225.0528870700129
Std:  15.001762798751782


Compute the **skewness** and **kurtosis**

You can use [`scipy.stats.skew`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.skew.html) and [`scipy.stats.kurtosis`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.kurtosis.html)

In [56]:
from scipy.stats import kurtosis, skew
from scipy import stats
scipy.stats. skew(samples)


0.06291320760863975

In [57]:
scipy.stats.kurtosis(samples)

-0.1195225972299454

## NumPy Correlation Calculation

Create an array x of integers between 10 (inclusive) and 20 (exclusive). Use `np.arange()`

In [59]:
x = np.arange(10,20)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

Then use `np.array()` to create a second array y containing 10 arbitrary integers.

In [64]:
y = np.array(x)
y

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

Once you have two arrays of the same length, you can compute the **correlation coefficient** between x and y

In [ ]:
r = 

## Pandas Correlation Calculation

Run the code below

In [60]:
x = pd.Series(range(10, 20))
y = pd.Series([2, 1, 4, 5, 8, 12, 18, 25, 96, 48])

Call the relevant method  to calculate Pearson's r correlation.

In [ ]:
r =

OPTIONAL. Call the relevant method to calculate Spearman's rho correlation.

In [ ]:
rho =

## Seaborn Dataset Tips

Import Seaborn Library

In [61]:
import seaborn as sns

Load "tips" dataset from Seaborn

In [62]:
tips = sns.load_dataset("tips")

Generate descriptive statistics include those that summarize the central tendency, dispersion

Call the relevant method to calculate pairwise Pearson's r correlation of columns